# https://docs.linuxserver.io/images/docker-openssh-server/
---
version: "2.1"
services:
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server
    hostname: openssh-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PUBLIC_KEY_FILE=./teun.key.pub
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=false
      - USER_NAME=teun
    volumes:
      - /Users/teun/shared/ssh-server/config:/config
    ports:
      - 2222:2222
    restart: unless-stopped
